### PR TITLE
upgraded to work with django 1.9+

### PR DESCRIPTION
**Pull request by bashu**
@vdboor can you check this one?

### CODE REVIEW

**Comment by bashu** [comment]
@vdboor we are using `fluentcms-emailtemplates` in production, can you release minor version with updates for django 1.9+?

**Comment by bashu** [comment]
@vdboor any progress?

**Comment by vdboor** [comment]
Wonderful, thanks a lot!

Sorry for being such hard to reach. I'm still struggling with the flood of GitHub notifications.

**Comment by bashu** [comment]
@vdboor thanks!

**Comment by vdboor** [comment]
@bashu You're welcome! I've also uploaded v1.0 to PyPI.

**Pull request merged**
